Removed HaCSHub Link
HaCSBCU/hacsbcu.github.io pull request #46
Opened 2017-08-14 18:13 UTC by luketainton

Closes #45

2017-08-14 18:14 UTC, PandelisZ approved these changes

2017-08-14 18:15 UTC, PandelisZ commented
! Ci doing its job

2017-08-14 18:16 UTC, luketainton commented
I don't actually see the problem it's reporting :/

2017-08-14 18:34 UTC, PandelisZ requested changes

2017-08-14 18:34 UTC, PandelisZ commented on index.html
> +          <a href="https://www.bcusu.com/organisation/9907/"><li>Membership <div class="nav-line"></div></li></a
here `</a>`

2017-08-15 08:46 UTC, PandelisZ approved these changes

2017-08-15 08:46 UTC, merged